### ISSUE TITLE
[Feature Request] Add support for CalDAV calendars

### ISSUE THREAD

**Issue by hanzei** [mharrend/matterbot-calendarBot#5]
I would love to see an integration of CalDAV calendars in calendarBot. CalDAV is one of the most used ways to access calendars on th web and is based on an open spec. Currently you are forced to use MS products what is not the best for an open source community

**Comment by mharrend** [comment]
@hanzei As usual with Open Source projects: If you have additional requirements, feel free to develop some additional code and then start a PR.
But do not expect that I or anyone else does it for you.

I developed the MS OWA since it fits in our environment and thought that the code would be a good starting point for others to hack the code, so that it fits in their environment.
However, it is beyond my time restricted possibilities to provide some user support.
Even though, I would also prefer an open source calendar protocol.

Hopefully, you understand this.
